participants:
    Solid:
        interfaces:
        - nodes-mesh: Solid-Mesh
          patch: INTERFACE
          read-data: [Force]
          write-data: [DisplacementDelta]
          
precice-config-file: ../precice-config.xml

